### ISSUE TITLE
Exception on launch

### ISSUE THREAD

**Issue by fego** [vaemendis/hccd#5]
Hello,

when I launch the jar I have the following error : 

> java.lang.IllegalArgumentException: input == null!
> 	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
> 	at net.vaemendis.hccd.Tools.getApplicationIcons(Tools.java:13)
> 	at net.vaemendis.hccd.ErrorDialog.show(ErrorDialog.java:69)
> 	at net.vaemendis.hccd.Hccd.main(Hccd.java:17)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at com.jdotsoft.jarloader.JarClassLoader.invokeMain(JarClassLoader.java:801)
> 	at net.vaemendis.hccd.Launcher.main(Launcher.java:10)

Tested with jdk 9. No pb with jdk8 on another computer.

I have downloaded the code and launched it with eclipse oxygen, and I had the same error. To correct it i changed the line 11 of the Tools class : 

`Object o = new Object();`
to
`Object o = new Tools();`

With this change it was ok.

Regards

**Comment by doublesupercool** [comment]
Confirmed, I have the same error with JDK 9.0.1

> java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at net.vaemendis.hccd.Tools.getApplicationIcons(Tools.java:13)
	at net.vaemendis.hccd.ErrorDialog.show(ErrorDialog.java:69)
	at net.vaemendis.hccd.Hccd.main(Hccd.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.jdotsoft.jarloader.JarClassLoader.invokeMain(JarClassLoader.java:801)
	at net.vaemendis.hccd.Launcher.main(Launcher.java:10)

**Comment by vaemendis** [comment]
Fixed.
Thanks for the analysis !
